<?php 
	/* @var $vo Vo_MarkerType */ 
    $vo = $this->vo; 
?>
.zoom-lt-50 .cfm-marker-<?php echo $vo->cssName ?> .cfm-inner,.cfm-legend .cfm-marker-<?php echo $vo->cssName ?> {background-color: <?php echo $vo->markerColor ?>;}
.zoom-lt-50 .cfm-marker-<?php echo $vo->cssName ?> .cfm-inner:hover,.zoom-lt-50 .cfm-marker-<?php echo $vo->cssName ?>.cfm-selected .cfm-inner{background-color: <?php echo $vo->markerHoveredColor ?>;}
