<?php 
	/* @var $vo Vo_Marker */ 
    $vo = $this->vo; 
    $dictEntries = $this->partial()->view->dictEntries; 
    
    $iconObj = $vo->icon ? $vo->icon : $vo->_type->defaultIcon;
	
    $paramsNeeded = false;
	
	//check that any param is needed to show
	for ($i = 1; $i <= Model_MarkerTypeMapper::PARAMS_NUM; $i++) {
		$value = $vo->{'param'. $i . 'Value'};
		
		if ($value && strpos($value, '||||||||') === false) //not empty link too checks
			$paramsNeeded = true;
	}	
?>
<div class="cfm-inner">
  <div class="cfm-title-params">
	<span class="cfm-icon">
	 <img src="<?php echo $iconObj->url; ?>" width="<?php echo $iconObj->width; ?>" height="<?php echo $iconObj->height; ?>" />
	</span>
	<span class="cfm-title"><?php echo $this->escape($vo->title); ?></span>
  </div>	
<?php 
    if($vo->image || $paramsNeeded)
    { 
?>
  <table class="cfm-params">
    <tbody>
    <tr>
<?php if ($vo->image) :?>
     <td class="cfm-image" style="width: <?php echo $vo->image->width ?>px;"><img src="<?php echo $vo->image->url ?>" /></td>
<?php endif; ?>
<?php if ($paramsNeeded) :?>
     <td class="cfm-custom-params">
    <?php 
        $pContent = array(); // params content used to store all data form params key is number
        $visibleNums = array();
        /* @var $paramVo Vo_MarkerTypeParam */
        foreach ($vo->_type->params as $paramVo)
        {
            $num = $paramVo->number;
            $varName = 'param' .$num . 'Value';
            if (!$vo->$varName) //no value for this param
                continue;
                
            //store which numbers are visible at 100%
            if ($paramVo->alwaysVisible) 
                array_push($visibleNums, $num);

                
            if ($paramVo->type == 'text'){
                $pContent[$num] = $this->escape($vo->$varName);
			}
            else if ($paramVo->type == 'dictionary'){ //get from dictionary
                $pContent[$num] = $this->escape($dictEntries[$paramVo->typeValue][$vo->$varName]->value);
			}
            else if ($paramVo->type == 'longText')
            { 
                $pContent[$num] = $this->longTextLink($vo->$varName, $paramVo->label);
                continue; //label inluded already
            }     
			else if ($paramVo->type == 'link')
            { 
				$pContent[$num] = $this->link($vo->$varName);
            }
                
            if ($paramVo->showLabel)
               $pContent[$num] = '<span class="cfm-param-label">'. $this->escape($paramVo->label) .'</span>&nbsp;'.$pContent[$num];
        }
        
        foreach ($pContent as $number => $content)
        {
            echo '
            <div class="cfm-param'. $number;
            if ( in_array($number, $visibleNums) )
            {
               echo ' cfm-param-visible';
               if ($number == $visibleNums[0])
                 echo ' cfm-param-first-visible';
                 
               if ($number == end($visibleNums))
                 echo ' cfm-param-last-visible';
            }
            echo '">'.$content.'</div>';
        }
    ?>
    
      </td>
<?php endif; ?>
    </tr>
    </tbody>
  </table>
	<?php } ?>
</div>